taiki-e/pin-project

.travis.yml, CHANGELOG.md, Cargo.toml, src/compile_fail/unpin_conflict.rs, src/lib.rs, tests/test.rs
There is a restriction that `unsafe_project` cannot support the tuple structs, so it will be optional in the future. In this change, we will prepare for that.
=> Make unsafe_fields to be able to opt-out

.travis.yml, CHANGELOG.md, Cargo.toml, README.md, src/enums.rs, src/fields.rs, src/lib.rs, src/macros.rs, src/structs.rs, src/utils.rs, src/variants.rs, tests/test.rs
See rust-lang-nursery/pin-utils#21
~~This has not been completed, but~~ this will make the following changes:
* Add the feature to create projected enums to `unsafe_project`.
* Add ~~a macro and~~ an attribute to support pattern matching.
=> More ergonomic enum support

pin-project-internal/src/lib.rs, pin-project-internal/src/pin_projectable/mod.rs, src/lib.rs, tests/repr_packed.rs, tests/ui/pin_projectable/auxiliary/sneaky_macro.rs, tests/ui/pin_projectable/packed.rs, tests/ui/pin_projectable/packed.stderr, tests/ui/pin_projectable/packed_sneaky.rs, tests/ui/pin_projectable/packed_sneaky.stderr
As described in issue https://github.com/taiki-e/pin-project/issues/32,
it's possible to bypass the #[repr(packed)] check via the use of an
additional procedural macro. However, we need to be able to forbid
using #[repr(packed) in order to make #[pin_projectable] sound
To enforce this, we can make use of the fact that taking references to
the fields of a #[repr(packed)] struct is unsafe. Given a #[repr(packed)]
struct Foo, we can generate code like this:
```rust
fn check_Foo(val: Foo) {
&val.field1;
&val.field2;
...
&val.fieldn;
}
```
If `Foo` turns out to be #[repr(packed)], the compiler will generate an
error for us, since none of the field references are in an `unsafe`
block.
Unfortunately, this check requires that at least one of the struct's
fields have an alignment greater than 1. …
=> Ensure that #[repr(packed)] cannot be used on #[pin_projectable] structs

pin-project-internal/src/lib.rs, pin-project-internal/src/pin_project/enums.rs, pin-project-internal/src/pin_project/mod.rs, pin-project-internal/src/pin_project/structs.rs, pin-project-internal/src/utils.rs, src/lib.rs, tests/pin_project.rs, tests/pinned_drop.rs, tests/project.rs
Based on https://github.com/rust-lang/unsafe-code-guidelines/issues/148#issuecomment-523711778
by @CAD97
Currently, the generated 'project' method takes a 'Pin<&mut Self>',
consuming it. This makes it impossible to use the original Pin<&mut Self>
after calling project(), since the 'Pin<&mut Self>' has been moved into
the the 'Project' method.
This makes it impossible to implement useful pattern when working with
enums:
```rust
enum Foo {
Variant1(#[pin] SomeFuture),
Variant2(OtherType)
}
fn process(foo: Pin<&mut Foo>) {
match foo.project() {
__FooProjection(fut) => {
fut.poll();
let new_foo: Foo = ...;
foo.set(new_foo);
},
_ => {}
}
}
```
This pattern is common when implementing a Future combinator - an inner
future is polled, and then the containing enum is changed to a new
variant. …
=> Make generated 'project' reference take an '&mut Pin<&mut Self>'

pin-project-internal/src/lib.rs, pin-project-internal/src/pin_project/mod.rs, pin-project-internal/src/pinned_drop.rs, pin-project-internal/src/project.rs, pin-project-internal/src/utils.rs, tests/project.rs
This adds a feature to convert an annotated impl to a projected type's impl.
Example:
```rust
#[project]
impl<T, U> Foo<T, U> {
fn baz(self) {
let Self { future, field } = self;
}
}
// convert to:
impl<'_pin, T, U> __FooProjection<'_pin, T, U> {
fn baz(self) {
let Self { future, field } = self;
}
}
```
Closes #43
cc @Nemo157
=> Add impl block support to #[project] attribute

pin-project-internal/src/lib.rs, pin-project-internal/src/pin_project/mod.rs, tests/pin_project.rs, tests/ui/pin_project/drop_conflict.stderr
Previously, we would provide an empty Drop impl for types that did not
provide a pinned_drop method, in order to assert that the user was not
providing their own Drop impl.
However, the compiler places certain restrictions on types that
implement Drop. For example, you cannot move out of the fields of such
types, as that would cause the Drop impl to observe the fields in an
uninitialized state.
This commit changes to a purely trait-based approach, as used in
the assert-impl crate by @upsuper . This prevents the creation of
unnecessary Drop impls, while still ensuring that the user cannot
provide their own Drop impl without going through pinned_drop
=> Assert lack of Drop impl without implementing Drop

pin-project-internal/src/project.rs, tests/project.rs
Previously, the #[project] attribute would only apply to plain 'match'
expressions, not 'match' expressions immediately assigned to a local.
This commit checks for #[project] attributes in the initializer of a
'let' expression, if the initializer is a 'match' expression.
=> Support #[project] attribute on 'let var = match' exressions

.gitignore, pin-project-internal/build.rs, pin-project-internal/src/lib.rs, pin-project-internal/src/pin_project/mod.rs
Apart from what I mentioned in https://github.com/taiki-e/pin-project/pull/53#issuecomment-525974922, there are cases where you want to completely avoid using the nightly function in the first place.
Refs: https://github.com/alexcrichton/proc-macro2/issues/175
=> Detect if the proc_macro_def_site feature is not disallowed by -Zallow-features

pin-project-internal/src/pin_project/enums.rs, pin-project-internal/src/pin_project/structs.rs
This prevents users from seing pointless, unsuppressible warnings in
their build
=> Apply #[allow(dead_code)] to generated types

pin-project-internal/src/lib.rs, pin-project-internal/src/pin_project/enums.rs, pin-project-internal/src/pin_project/mod.rs, pin-project-internal/src/pin_project/structs.rs, pin-project-internal/src/utils.rs, tests/pin_project.rs
This method consumes takes a 'Pin<&mut Self>' by value, instead
of by mutable reference. This allows us to give the projection
struct/enum a longer lifetime, which is required when returning it
from a function
Fixes #65
=> Add 'project_into' method to #[pin_project] types

azure-pipelines.yml, pin-project-internal/Cargo.toml, pin-project-internal/build.rs, pin-project-internal/src/pin_project/mod.rs, src/lib.rs, tests/compiletest.rs, tests/ui/pin_project/proper_unpin.stderr, tests/ui/pin_project/unpin_sneaky.rs, tests/ui/pin_project/unpin_sneaky.stderr
There are some problems as mentioned in #70 
This causes the problem that by default the actual Unpin bounds cannot be known from the document if the original struct/enum itself is public (see https://github.com/taiki-e/pin-project/pull/53#issuecomment-525906867 and https://github.com/rust-lang/rust/issues/63281 for more).
This can be enabled using `--cfg pin_project_show_unpin_struct` in RUSTFLAGS.
```toml
[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "pin_project_show_unpin_struct"]
```
cc @Aaron1011 @seanmonstar @LucioFranco
=> Do not display UnpinStruct in the document by default

README.md, examples/enum-default-expanded.rs, examples/pinned_drop-expanded.rs, examples/pinned_drop.rs, examples/struct-default-expanded.rs, examples/unsafe_unpin-expanded.rs, pin-project-internal/src/lib.rs, pin-project-internal/src/pin_project/attribute.rs, pin-project-internal/src/utils.rs, src/lib.rs, tests/pin_project.rs, tests/pinned_drop.rs, tests/project.rs, tests/ui/project/ambiguous-let.rs, tests/ui/project/ambiguous-let.stderr, tests/ui/project/invalid.rs, tests/ui/project/invalid.stderr, tests/ui/project/stmt_expr_attributes.rs
=> Change the argument type of project method back to `self: Pin<&mut Self>`

Cargo.toml, pin-project-internal/Cargo.toml, pin-project-internal/src/lib.rs, src/lib.rs, tests/compiletest.rs, tests/project.rs
=> Remove "project_attr" feature and always enable #[project] attribute

pin-project-internal/src/lib.rs, pin-project-internal/src/project.rs, tests/project.rs, tests/ui/project/use-public.rs, tests/ui/project/use-public.stderr, tests/ui/project/use.rs, tests/ui/project/use.stderr
This adds a feature to convert annotated imports to a projected type's imports.
~~For now, this works as an import for both projected type and projection trait.~~ Now, this works as an import for projected type.
```rust
use pin_project::pin_project;
#[pin_project]
struct Foo<A> {
#[pin]
field: A,
}
mod bar {
use pin_project::project;
use super::Foo;
use std::pin::Pin;
#[project]
use super::Foo;
#[project]
fn baz<A>(foo: Pin<&mut Foo<A>>) {
#[project]
let Foo { field } = foo.project();
let _: Pin<&mut A> = field;
}
}
```
=> Add use statements support to #[project] attribute

examples/enum-default-expanded.rs, examples/pinned_drop-expanded.rs, examples/struct-default-expanded.rs, examples/unsafe_unpin-expanded.rs, pin-project-internal/src/lib.rs, pin-project-internal/src/pin_project/attribute.rs, pin-project-internal/src/project.rs, pin-project-internal/src/utils.rs, src/lib.rs, tests/pin_project.rs, tests/project_ref.rs
=> Add project_ref method and #[project_ref] attribute

Cargo.toml, ci/azure-test.yml, pin-project-internal/Cargo.toml, pin-project-internal/src/lib.rs, pin-project-internal/src/pin_project/attribute.rs, pin-project-internal/src/pinned_drop.rs, pin-project-internal/src/utils.rs
Unlike using `$crate` with declarative macros, re-export of procedural macros are not supported even if `proc-macro-crate` is used.
Also, crate name matches the macro name, so I don't think there is a need to rename it.
Related: https://github.com/taiki-e/pin-project/pull/18#discussion_r307995504
=> Remove "renamed" feature

README.md, examples/unsafe_unpin-expanded.rs, pin-project-internal/src/lib.rs, pin-project-internal/src/pin_project/attribute.rs, src/lib.rs, tests/ui/unsafe_unpin/not-implement-unsafe-unpin.rs, tests/ui/unsafe_unpin/not-implement-unsafe-unpin.stderr, tests/ui/unsafe_unpin/proper_unpin.rs, tests/ui/unsafe_unpin/proper_unpin.stderr, tests/ui/unstable-features/trivial_bounds-feature-gate.rs, tests/ui/unstable-features/trivial_bounds-feature-gate.stderr, tests/unsafe_unpin.rs
If we know that `Self` doesn't implement `Unpin` and `Self` doesn't contain any
generics or lifetimes, we get an error `E0277`.
To avoid this, add a dummy lifetime to the `Wrapper`. This allows
`Wrapper<Self>` to always compile regardless of whether `Self`
implements `UnsafeUnpin`.
As the `Wrapper` implements `UnsafeUnpin` regardless of a lifetime, this
should not change the actual bounds of the `Unpin` implementation.
This allows workaround of #102 that "using `pin_project(UnsafeUnpin)`
and not providing a manual `UnsafeUnpin` implementation" to work.
Closes #102 
cc @Aaron1011 @ogoffart
=> Add a dummy lifetime to Wrapper

examples/pinned_drop-expanded.rs, examples/struct-default-expanded.rs, examples/unsafe_unpin-expanded.rs, pin-project-internal/src/pin_project/attribute.rs, tests/pin_project.rs, tests/ui/pin_project/packed_sneaky-2.rs, tests/ui/pin_project/packed_sneaky-2.stderr
=> Fix support for DSTs

src/lib.rs
Now that rust-lang/rust#64536 has landed, all of the bugs with proc
macro documentation have now been fixed (currently only on the latest
nightly). We can now use `#[doc(inline)]` on proc macro imports, which
works just like any other import.
=> Properly inline documentation and use intra-crate lints

src/lib.rs, tests/unsafe_unpin.rs
=> Fix support for DSTs on #[pin_project(UnsafeUnpin)]

pin-project-internal/src/lib.rs, src/lib.rs
This issue has been fixed in #98.
=> Remove outdated TODO comments

.github/workflows/ci.yml, compiletest.sh, tests/compiletest.rs
This may reduce CI time because dependencies are recompiled each time `RUSTFLAGS` is changed.
=> Avoid recompilation with compiletest

.github/workflows/ci.yml
This is the minimum Rust version we can actually run tests on because the current test depends on the elision rules introduced in https://github.com/rust-lang/rust/pull/61207.
=> Run tests on Rust 1.36

.github/bors.toml
=> Add Rust 1.36 test to the merge requirement of bors

examples/pinned_drop-expanded.rs, pin-project-internal/src/pinned_drop.rs, tests/pinned_drop.rs, tests/ui/pin_project/self-in-where-clause.rs, tests/ui/pin_project/self-in-where-clause.stderr, tests/ui/pinned_drop/ref-self.rs, tests/ui/pinned_drop/ref-self.stderr, tests/ui/pinned_drop/self-match.rs, tests/ui/pinned_drop/self-match.stderr, tests/ui/pinned_drop/unsafe-code.rs, tests/ui/pinned_drop/unsafe-code.stderr
This change will generate code similar to the following:
from:
```rust
impl PinnedDrop for Foo {
fn drop(self: Pin<&mut Self>) {
// ...
}
}
```
into:
```rust
impl PinnedDrop for Foo {
unsafe fn drop(self: Pin<&mut Self>) {
fn __drop_inner<T>(__self: Pin<&mut Foo<'_, T>>) {
// ...
}
__drop_inner(self);
}
}
```
Fixes #148
=> Fix an issue where PinnedDrop implementations can call unsafe code without an unsafe block

examples/pinned_drop-expanded.rs, examples/unsafe_unpin-expanded.rs, pin-project-internal/src/lib.rs, pin-project-internal/src/pinned_drop.rs, src/lib.rs, tests/ui/auxiliary/src/lib.rs
I think pedantic lints are no longer useful.
=> Remove #![warn(clippy::pedantic)]

pin-project-internal/src/pin_project/derive.rs, tests/ui/pin_project/run-pass/dyn-type.rs
Add parentheses around original types in generated code.
Currently, it will cause a compile error when field type is like `dyn Trait1 + Trait2`.
```rust
use pin_project::pin_project;
#[pin_project]
struct Struct {
a: i32,
#[pin]
f: dyn std::fmt::Debug + Send,
}
```
will result in,
```
error: ambiguous `+` in a type
--> src/main.rs:6:8
|
6 |     f: dyn std::fmt::Debug + Send,
|        ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use parentheses to disambiguate: `(dyn std::fmt::Debug + Send)`
error: proc-macro derive produced unparseable tokens
--> src/main.rs:2:1
|
2 | #[pin_project]
| ^^^^^^^^^^^^^^
```
=> Fix compile error with `dyn` types

tests/pin_project.rs
pin-project(this repo) supports this, [pin-project-lite](https://github.com/taiki-e/pin-project) does not support this
Related: #170
=> Add test for ?Sized in where clause

pin-project-internal/src/pin_project/derive.rs, tests/ui/pinned_drop/pinned-drop-no-attr-arg.rs, tests/ui/pinned_drop/pinned-drop-no-attr-arg.stderr
Fixes #179
Previously, it was possible to provide a `#[pinned_drop]` implementation
without annotating the pin-projected type with
`#[pin_project(PinnedDrop)]`. This would result in the `PinnedDrop` impl
never being used, without any warnings or errors being emitted to the
user.
This commit makes us generate a dummy `PinnedDrop` impl if the user does
not pass `PinnedDrop` as an argument to `#[pin_project]`. This dummy
impl will conflict with any user-provided impl, ensuring that the user
cannot accidentally a non-functional `PinnedDrop` impl.
=> Ensure that users cannot implement `PinnedDrop` without proper attr

tests/ui/pin_project/safe_packed_borrows.stderr, tests/ui/unstable-features/overlapping_marker_traits.rs, tests/ui/unstable-features/overlapping_marker_traits.stderr, tests/ui/unstable-features/trivial_bounds-bug.stderr, tests/ui/unstable-features/trivial_bounds-feature-gate.stderr, tests/ui/unstable-features/trivial_bounds.stderr
=> Update ui tests

pin-project-internal/src/project.rs, tests/project.rs, tests/project_if_attr.rs.in
This PR would work correctly, except for the fact that
rust-lang/rust#68618 causes a compilation error to be emitted before we
even have a chance to run. That issue is independent of the
implementation of this PR, so this PR should start working automatically
once the issue is resolved.
=> Allow `#[project]` to be used on `if let` expressions

pin-project-internal/src/pin_project/derive.rs, tests/project.rs
Previously, we were generating the `where` clause in the wrong position
for the generated projection struct, leading to a compilation error.
=> Properly handle `where` clauses on tuple structs

.github/workflows/ci.yml, compiletest.sh, examples/enum-default-expanded.rs, examples/pinned_drop-expanded.rs, examples/struct-default-expanded.rs, examples/unsafe_unpin-expanded.rs, pin-project-internal/src/lib.rs, pin-project-internal/src/pin_project/derive.rs, tests/compiletest.rs, tests/ui/cfg/cfg_attr-unpin.stderr, tests/ui/cfg/proper_unpin.stderr, tests/ui/pin_project/add-pinned-field.stderr, tests/ui/pin_project/conflict-drop.stderr, tests/ui/pin_project/overlapping_unpin_struct.stderr, tests/ui/pin_project/proper_unpin.stderr, tests/ui/pin_project/unpin_sneaky.stderr
Generate all items except for projected types inside a `const` scope. This makes it impossible for user code to refer to these types. This removes redundant prefix/postfix based on the original type from many generate types. This also remove the `pin_project_show_unpin_struct` flag.
=> Hide all generated items except for projected types from calling code

.github/workflows/ci.yml, Cargo.toml, ci.sh, tests/expand/Cargo.toml, tests/expand/build.rs, tests/expand/tests/enum/enum-default.expanded.rs, tests/expand/tests/enum/enum-default.rs, tests/expand/tests/expandtest.rs, tests/expand/tests/struct/pinned_drop.expanded.rs, tests/expand/tests/struct/pinned_drop.rs, tests/expand/tests/struct/struct-default.expanded.rs, tests/expand/tests/struct/struct-default.rs, tests/expand/tests/struct/unsafe_unpin.expanded.rs, tests/expand/tests/struct/unsafe_unpin.rs
Similar to ui tests, but instead of checking the compiler output, this checks the code generated by proc-macro.
Refs: https://github.com/eupn/macrotest
=> Add expansion tests

pin-project-internal/src/project.rs, tests/pin_project.rs, tests/project.rs, tests/project_if_attr.rs.in
=> Fix #[project] attribute on non-statement expressions

examples/enum-default-expanded.rs, examples/pinned_drop-expanded.rs, examples/pinned_drop.rs, examples/struct-default-expanded.rs, examples/unsafe_unpin-expanded.rs, examples/unsafe_unpin.rs, pin-project-internal/src/pin_project/derive.rs, pin-project-internal/src/pinned_drop.rs, pin-project-internal/src/utils.rs, src/lib.rs, tests/expand/tests/enum/default.expanded.rs, tests/expand/tests/enum/project_replace.expanded.rs, tests/expand/tests/struct/default.expanded.rs, tests/expand/tests/struct/pinned_drop.expanded.rs, tests/expand/tests/struct/pinned_drop.rs, tests/expand/tests/struct/project_replace.expanded.rs, tests/expand/tests/struct/unsafe_unpin.expanded.rs, tests/expand/tests/struct/unsafe_unpin.rs, tests/overwriting_core_crate.rs
See https://github.com/rust-lang/pin-utils/pull/26#discussion_r344491597
Note: If the proc-macro does not depend on its own items, it may be preferable not to
support overwriting the name of core/std crate for compatibility with reexport.
=> Support overwriting the name of core crate

examples/pinned_drop-expanded.rs, pin-project-internal/src/pinned_drop.rs, src/lib.rs, tests/clippy.rs, tests/expand/tests/struct/pinned_drop.expanded.rs
This lint does not warn the receiver.
=> Add #[allow(clippy::needless_pass_by_value)] to drop_inner

pin-project-internal/src/project.rs, tests/project.rs
Fixes #206 and https://github.com/hyperium/hyper/issues/2199
=> Do not skip visiting nested expressions

tests/ui/pinned_drop/conditional-drop-impl.rs, tests/ui/pinned_drop/conditional-drop-impl.stderr
In `Drop` impl, the implementor must specify the same requirement as type definition. 
We cannot make `PinnedDrop` generate the same error message, but it seems rustc print out a useful help message.
`Drop`:
```txt
error[E0367]: `Drop` impl requires `T: std::marker::Unpin` but the struct it is implemented for does not
--> $DIR/conditional-drop-impl.rs:10:9
|
10 | impl<T: Unpin> Drop for DropImpl<T> {
|         ^^^^^
|
note: the implementor must specify the same requirement
--> $DIR/conditional-drop-impl.rs:6:1
|
6  | / struct DropImpl<T> {
7  | |     field: T,
8  | | }
| |_^
```
`PinnedDrop`:
```txt
error[E0277]: `T` cannot be unpinned
--> $DIR/conditional-drop-impl.rs:15:15
|
15 | #[pin_project(PinnedDrop)] //~ ERROR E0277
|               ^^^^^^^^^^ the trait `std::marker::Unpin` is not …
```
=> Add ui test for conditional drop impl

examples/enum-default-expanded.rs, examples/pinned_drop-expanded.rs, examples/struct-default-expanded.rs, examples/unsafe_unpin-expanded.rs, pin-project-internal/src/pin_project/derive.rs, tests/expand/tests/enum/default.expanded.rs, tests/expand/tests/enum/project_replace.expanded.rs, tests/expand/tests/struct/default.expanded.rs, tests/expand/tests/struct/pinned_drop.expanded.rs, tests/expand/tests/struct/project_replace.expanded.rs, tests/expand/tests/struct/unsafe_unpin.expanded.rs
All of the generated items are private items, but it can be displayed in the document by using the `--document-private-items` flag.
Naming will be allowed by #202, so it would probably be preferable to only display it in the document if the user did a naming.
cc #124 #202
Related: https://github.com/taiki-e/pin-project/pull/192
=> Hide generated items from --document-private-items

.github/workflows/ci.yml, pin-project-internal/src/project.rs, tests/expand/Cargo.toml, tests/expand/tests/expandtest.rs, tests/project.rs, tests/project_ref.rs, tests/project_replace.rs, tests/ui/project/invalid.rs, tests/ui/project/invalid.stderr
Addresses https://github.com/rust-lang/futures-rs/pull/2148#discussion_r422663305
=> Handle all project* attributes in that scope with one wrapper attribute

examples/pinned_drop-expanded.rs, pin-project-internal/src/pinned_drop.rs, tests/expand/tests/expand/pinned_drop-enum.expanded.rs, tests/expand/tests/expand/pinned_drop-struct.expanded.rs, tests/expand/tests/expand/pinned_drop-tuple_struct.expanded.rs, tests/ui/pinned_drop/call-drop-inner.rs, tests/ui/pinned_drop/call-drop-inner.stderr
This is an internal function, and the user should not be able to call this. Ideally, we should use a def-site span, but we can't do that, so add a dummy `__drop_inner` function at the beginning of `__drop_inner` function.
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ee4d5e2621a61d510b63ab0d7a18bb98)
=> Prevent user call `__drop_inner`

examples/enum-default-expanded.rs, examples/enum-default.rs, pin-project-internal/src/lib.rs, pin-project-internal/src/pin_project/derive.rs, tests/expand/tests/expand/naming-enum.expanded.rs, tests/expand/tests/expand/naming-enum.rs, tests/expand/tests/expand/naming-struct.expanded.rs, tests/expand/tests/expand/naming-struct.rs, tests/expand/tests/expand/naming-tuple_struct.expanded.rs, tests/expand/tests/expand/naming-tuple_struct.rs, tests/pin_project.rs, tests/ui/pin_project/conflict-naming.rs, tests/ui/pin_project/conflict-naming.stderr, tests/ui/pin_project/invalid.rs, tests/ui/pin_project/invalid.stderr, tests/ui/pin_project/visibility.rs, tests/ui/pin_project/visibility.stderr
By passing an argument with the same name as the method to the attribute, you can name the projection type returned from the method:
```rust
#[pin_project(
Replace,
project = StructProj,
project_ref = StructProjRef,
project_replace = StructProjOwn,
)]
struct Struct<T> {
#[pin]
field: T,
}
let mut x = Struct { field: 0 };
let StructProj { field } = Pin::new(&mut x).project();
let StructProjRef { field } = Pin::new(&x).project_ref();
let StructProjOwn { field } = Pin::new(&mut x).project_replace(Struct { field: 1 });
```
cc #43
Closes #124
TODO:
=> Allow naming the projected types

pin-project-internal/src/utils.rs, tests/ui/pinned_drop/self.rs, tests/ui/pinned_drop/self.stderr
The following code:
```rust
use pin_project::{pin_project, pinned_drop};
use std::pin::Pin;
#[pin_project(PinnedDrop)]
pub struct Struct {
x: (),
}
#[pinned_drop]
impl PinnedDrop for Struct {
fn drop(self: Pin<&mut Self>) {
let _: Self = Self;
}
}
```
The error message points to wrong span:
```text
error[E0423]: expected value, found struct `Struct`
--> src/lib.rs:10:21
|
10 | impl PinnedDrop for Struct {
|                     ^^^^^^ did you mean `(Struct { /* fields */ })`?
|
```
This PR fixes span of Self keyword to make the error message to point to the correct span:
```text
error[E0423]: expected value, found struct `Struct`
--> $DIR/self.rs:38:27
|
30 | /     pub struct Struct {
31 | |         x: (),
32 | |     }
| |_____- `Struct` defined here
...
38 |               let _: Self = …
```
=> Preserve span of Self keyword

pin-project-internal/src/utils.rs, tests/ui/pinned_drop/self.rs, tests/ui/pinned_drop/self.stderr
A similar case to #235.
The following code:
```rust
use pin_project::{pin_project, pinned_drop};
use std::pin::Pin;
#[pin_project(PinnedDrop)]
pub enum E {
V { x : () }
}
#[pinned_drop]
impl PinnedDrop for Struct {
fn drop(self: Pin<&mut Self>) {
let _: Self = Self::V;
}
}
```
The error message points to call-site span:
```text
error[E0533]: expected unit struct, unit variant or constant, found struct variant `#[pinned_drop]`
--> $DIR/self.rs:47:5
|
47 |     #[pinned_drop]
|     ^^^^^^^^^^^^^^
|
```
This PR fixes span of `<` and `>` tokens of `QSelf` to make the error message to point to the correct span:
```text
error[E0533]: expected unit struct, unit variant or constant, found struct variant `Self::V`
--> $DIR/self.rs:51:27
|
51 |             let _: Self = Self::V;
| …
```
=> Propagate the span of Self keyword to QSelf

pin-project-internal/src/pinned_drop.rs, tests/pinned_drop.rs
Refs: https://github.com/dtolnay/async-trait/pull/105
`#[pinned_drop]` attribute also has same issue.
=> Preserve the span of self argument

pin-project-internal/src/pin_project/attribute.rs, pin-project-internal/src/pin_project/derive.rs, pin-project-internal/src/pinned_drop.rs, pin-project-internal/src/utils.rs, tests/ui/auxiliary/lib.rs
https://docs.rs/syn/1.0.31/syn/token/index.html
> The type names in this module can be difficult to keep straight, so we prefer to use the `Token!` macro instead. This is a type-macro that expands to the token type of the given token.
=> Use Token macro instead of concrete token type names

CHANGELOG.md, pin-project-internal/build.rs, pin-project-internal/src/lib.rs, src/lib.rs, tests/project.rs, tests/project_ref.rs, tests/project_replace.rs, tests/ui/project/ambiguous-let.rs, tests/ui/project/ambiguous-let.stderr, tests/ui/project/deprecated.rs, tests/ui/project/deprecated.stderr, tests/ui/project/invalid.rs, tests/ui/project/invalid.stderr, tests/ui/project/type-mismatch.rs, tests/ui/project/type-mismatch.stderr, tests/ui/project/use-public.rs, tests/ui/project/use-public.stderr, tests/ui/project/use.rs, tests/ui/project/use.stderr, tests/ui/unstable-features/run-pass/stmt_expr_attributes.rs, tests/ui/unstable-features/stmt_expr_attributes-feature-gate.rs, tests/ui/unstable-features/stmt_expr_attributes-feature-gate.stderr
This deprecates `#[project]`, `#[project_ref]`, and `#[project_replace]` attributes in favor of the naming of projected type.
Closes #225
=> Deprecate project* attributes

pin-project-internal/src/pin_project/derive.rs
`as_ref().cloned()` is redundant: https://doc.rust-lang.org/1.44.1/src/core/option.rs.html#1276-1292
=> Replace Option::as_ref().cloned() with Option::clone()

pin-project-internal/src/pin_project/derive.rs, tests/ui/pin_project/invalid.rs, tests/ui/pin_project/invalid.stderr
=> Remove Replace argument

examples/enum-default-expanded.rs, examples/not_unpin-expanded.rs, examples/pinned_drop-expanded.rs, examples/project_replace-expanded.rs, examples/struct-default-expanded.rs, examples/unsafe_unpin-expanded.rs, pin-project-internal/src/pin_project/derive.rs, tests/expand/tests/expand/default-enum.expanded.rs, tests/expand/tests/expand/default-struct.expanded.rs, tests/expand/tests/expand/default-tuple_struct.expanded.rs, tests/expand/tests/expand/not_unpin-enum.expanded.rs, tests/expand/tests/expand/not_unpin-struct.expanded.rs, tests/expand/tests/expand/not_unpin-tuple_struct.expanded.rs, tests/expand/tests/expand/pinned_drop-enum.expanded.rs, tests/expand/tests/expand/pinned_drop-struct.expanded.rs, tests/expand/tests/expand/pinned_drop-tuple_struct.expanded.rs, tests/expand/tests/expand/project_replace-enum.expanded.rs, tests/expand/tests/expand/project_replace-struct.expanded.rs, tests/expand/tests/expand/project_replace-tuple_struct.expanded.rs, tests/expand/tests/expand/pub-enum.expanded.rs, tests/expand/tests/expand/pub-struct.expanded.rs, tests/expand/tests/expand/pub-tuple_struct.expanded.rs, tests/expand/tests/expand/unsafe_unpin-enum.expanded.rs, tests/expand/tests/expand/unsafe_unpin-struct.expanded.rs, tests/expand/tests/expand/unsafe_unpin-tuple_struct.expanded.rs, tests/ui/pin_project/import_unnamed.rs, tests/ui/pin_project/import_unnamed.stderr, tests/ui/pin_project/visibility.rs, tests/ui/pin_project/visibility.stderr
Defines projected types in inside `const _: () = {}` when the users don't name it;
cc #264
=> Do not expose unnamed projected types

examples/enum-default-expanded.rs, pin-project-internal/src/lib.rs, pin-project-internal/src/pin_project/derive.rs, tests/cfg.rs, tests/expand/tests/expand/default-enum.expanded.rs, tests/expand/tests/expand/default-enum.rs, tests/expand/tests/expand/naming-enum-none.expanded.rs, tests/expand/tests/expand/naming-enum-none.rs, tests/expand/tests/expand/naming-enum-own.expanded.rs, tests/expand/tests/expand/naming-enum-ref.expanded.rs, tests/expand/tests/expand/naming-struct-none.expanded.rs, tests/expand/tests/expand/naming-struct-none.rs, tests/expand/tests/expand/naming-tuple_struct-none.expanded.rs, tests/expand/tests/expand/naming-tuple_struct-none.rs, tests/expand/tests/expand/not_unpin-enum.expanded.rs, tests/expand/tests/expand/not_unpin-enum.rs, tests/expand/tests/expand/pinned_drop-enum.expanded.rs, tests/expand/tests/expand/pinned_drop-enum.rs, tests/expand/tests/expand/project_replace-enum.expanded.rs, tests/expand/tests/expand/project_replace-enum.rs, tests/expand/tests/expand/pub-enum.expanded.rs, tests/expand/tests/expand/unsafe_unpin-enum.expanded.rs, tests/expand/tests/expand/unsafe_unpin-enum.rs, tests/include/basic-safe-part.rs, tests/lint.rs, tests/pin_project.rs, tests/pinned_drop.rs, tests/ui/pin_project/invalid.rs, tests/ui/pin_project/invalid.stderr
When `#[pin_project]` is used on enums, only named projection types and methods are generated because there is no way to access variants of projected types without naming it. (When `#[pin_project]` is used on structs, both methods are always generated.)
Addresses https://github.com/taiki-e/pin-project/pull/268#discussion_r484313531
=> Optimize code generation when used on enums

.github/workflows/ci.yml, tests/compiletest.rs, tests/lint.rs
The pin guarantees are guarantees of a library, so Miri does not detect
violations of the pin API. However, if the generated unsafe code causes
UB, Miri may be possible to detect it.
Related: https://github.com/rust-lang/miri/issues/823, https://github.com/rust-lang/unsafe-code-guidelines/issues/232#issuecomment-619572693
=> Run Miri on CI

pin-project-internal/src/pin_project/derive.rs, tests/drop_order.rs, tests/expand/tests/expand/multifields-enum.expanded.rs, tests/expand/tests/expand/multifields-enum.rs, tests/expand/tests/expand/multifields-struct.expanded.rs, tests/expand/tests/expand/multifields-struct.rs, tests/expand/tests/expand/multifields-tuple_struct.expanded.rs, tests/expand/tests/expand/multifields-tuple_struct.rs
The fields of the struct and the active enum variant are dropped in declaration order ([reference](https://doc.rust-lang.org/reference/destructors.html)).
The current `project_replace` drops pinned fields in reverse order of declaration ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5e2117bc64a648f254204d4e858bfb2a)), but this should be in the same order as dropping structs normally.
cc @Diggsey
=> Fix drop order of pinned fields in project_replace

pin-project-internal/src/pin_project/derive.rs, tests/drop_order.rs, tests/expand/tests/expand/multifields-enum.expanded.rs, tests/expand/tests/expand/multifields-enum.rs, tests/expand/tests/expand/multifields-struct.expanded.rs, tests/expand/tests/expand/multifields-struct.rs, tests/expand/tests/expand/multifields-tuple_struct.expanded.rs, tests/expand/tests/expand/multifields-tuple_struct.rs
=> v0.4: Fix drop order of pinned fields in project_replace

.gitattributes, tests/lint.rs, tests/lint.txt
This test is to make sure that the lint list (`tests/lint.txt`) is up to date, but [the output when it fails](https://github.com/taiki-e/pin-project/runs/1318282067?check_suite_focus=true) is bad and the fix was a bit annoying.
Context: 9cf58447084445407c358d7a0852495c5588efe0
=> Improve output of check_lint_list test when failed

examples/not_unpin-expanded.rs, examples/pinned_drop-expanded.rs, examples/project_replace-expanded.rs, examples/struct-default-expanded.rs, examples/unsafe_unpin-expanded.rs, pin-project-internal/src/pin_project/derive.rs, tests/expand/tests/expand/default-struct.expanded.rs, tests/expand/tests/expand/default-tuple_struct.expanded.rs, tests/expand/tests/expand/multifields-struct.expanded.rs, tests/expand/tests/expand/multifields-tuple_struct.expanded.rs, tests/expand/tests/expand/naming-struct.expanded.rs, tests/expand/tests/expand/naming-tuple_struct.expanded.rs, tests/expand/tests/expand/not_unpin-struct.expanded.rs, tests/expand/tests/expand/not_unpin-tuple_struct.expanded.rs, tests/expand/tests/expand/pinned_drop-struct.expanded.rs, tests/expand/tests/expand/pinned_drop-tuple_struct.expanded.rs, tests/expand/tests/expand/project_replace-struct.expanded.rs, tests/expand/tests/expand/project_replace-tuple_struct.expanded.rs, tests/expand/tests/expand/pub-struct.expanded.rs, tests/expand/tests/expand/pub-tuple_struct.expanded.rs, tests/expand/tests/expand/unsafe_unpin-struct.expanded.rs, tests/expand/tests/expand/unsafe_unpin-tuple_struct.expanded.rs
This fixes `unused_must_use` warning on unused borrows, which will be added to rustc in the future.
See https://github.com/rust-lang/rust/pull/76894 fore more.
(Note: pin-project 1.0 does not have this problem.)
=> v0.4: Fix unused_must_use warning on unused borrows

examples/not_unpin-expanded.rs, examples/pinned_drop-expanded.rs, examples/project_replace-expanded.rs, examples/struct-default-expanded.rs, examples/unsafe_unpin-expanded.rs, pin-project-internal/src/pin_project/derive.rs, tests/expand/tests/expand/default-struct.expanded.rs, tests/expand/tests/expand/default-tuple_struct.expanded.rs, tests/expand/tests/expand/multifields-struct.expanded.rs, tests/expand/tests/expand/multifields-tuple_struct.expanded.rs, tests/expand/tests/expand/naming-struct.expanded.rs, tests/expand/tests/expand/naming-tuple_struct.expanded.rs, tests/expand/tests/expand/not_unpin-struct.expanded.rs, tests/expand/tests/expand/not_unpin-tuple_struct.expanded.rs, tests/expand/tests/expand/pinned_drop-struct.expanded.rs, tests/expand/tests/expand/pinned_drop-tuple_struct.expanded.rs, tests/expand/tests/expand/project_replace-struct.expanded.rs, tests/expand/tests/expand/project_replace-tuple_struct.expanded.rs, tests/expand/tests/expand/pub-struct.expanded.rs, tests/expand/tests/expand/pub-tuple_struct.expanded.rs, tests/expand/tests/expand/unsafe_unpin-struct.expanded.rs, tests/expand/tests/expand/unsafe_unpin-tuple_struct.expanded.rs, tests/repr_packed.rs, tests/ui/pin_project/packed.rs, tests/ui/pin_project/packed.stderr, tests/ui/pin_project/safe_packed_borrows.rs, tests/ui/pin_project/safe_packed_borrows.stderr, tests/ui/pin_project/unaligned_references.rs, tests/ui/pin_project/unaligned_references.stderr
=> v0.4: Prepare for removal of safe_packed_borrows lint

examples/pinned_drop-expanded.rs, pin-project-internal/src/pinned_drop.rs, tests/expand/pinned_drop/enum.expanded.rs, tests/expand/pinned_drop/struct.expanded.rs, tests/expand/pinned_drop/tuple_struct.expanded.rs
`PinnedDrop` is a private trait and should not appear in docs.
=> Hide PinnedDrop impl from docs

CHANGELOG.md, pin-project-internal/src/utils.rs, tests/pinned_drop.rs
Based on https://github.com/dtolnay/async-trait/commit/6029cbf375c562ca98fa5748e9d950a8ff93b0e7
=> Preserve `self` as segment of path

.github/workflows/ci.yml, tests/ui/pin_project/project_replace_unsized.stderr, tests/ui/pin_project/project_replace_unsized_fn_params.stderr, tests/ui/pin_project/remove-attr-from-struct.stderr, tests/ui/unstable-features/trivial_bounds-bug.stderr, tests/ui/unstable-features/trivial_bounds-feature-gate.stderr
Some tests generate different diagnostics depending on whether this component is installed.
=> Install rust-src component for ui tests

pin-project-internal/src/pin_project/derive.rs, tests/auxiliary/macro/lib.rs, tests/ui/pin_project/packed_sneaky-1.rs, tests/ui/pin_project/packed_sneaky-1.stderr, tests/ui/pin_project/packed_sneaky-4.rs, tests/ui/pin_project/packed_sneaky-4.stderr
=> Add test for issue 342

pin-project-internal/src/pin_project/derive.rs, tests/expand/not_unpin/enum.expanded.rs, tests/expand/not_unpin/struct.expanded.rs, tests/expand/not_unpin/tuple_struct.expanded.rs
Hide the documentation of the `Unpin` implementation that guarantees `!Unpin` to avoid confusion.
Before:
After:
=> Hide documentation of the `Unpin` implementation for `!Unpin`
