taiki-e/pin-project

.travis.yml
CHANGELOG.md
Cargo.toml
src/fields.rs
src/lib.rs
src/structs.rs
src/utils.rs
src/variants.rs
tests/test.rs

This implements one of the ideas for supporting enums.
Closes #3

Add unsafe_variants attribute

---

src/unsafe_project/mod.rs
tests/ui/unsafe_project/unpin_conflict.stderr

Remove usage of quote_spanned

---

README.md
doc/enum-example-1.md
doc/struct-example-1.md
pin-project/src/lib.rs

Fix outdated examples

---

pin-project-internal/src/project.rs
src/lib.rs
tests/project.rs

This has many limitations.
cc #36

Remove support of if-let expressions from #[project] attribute

---

pin-project-internal/src/project.rs
pin-project-internal/src/utils.rs
src/lib.rs
tests/compile-test.rs
tests/pin_project.rs
tests/ui/project/type-mismatch.rs
tests/ui/project/type-mismatch.stderr

Simplify #[project] attribute and remove undocumented features

---

Cargo.toml
ci/azure-test.yml
pin-project-internal/Cargo.toml
pin-project-internal/src/lib.rs
src/lib.rs

Make #[project] attribute disabled by default

---

Cargo.toml
ci/azure-test.yml
pin-project-internal/Cargo.toml
pin-project-internal/src/lib.rs
pin-project-internal/src/pin_project/enums.rs
pin-project-internal/src/pin_project/mod.rs
pin-project-internal/src/pin_project/structs.rs
pin-project-internal/src/pinned_drop.rs
pin-project-internal/src/project.rs
pin-project-internal/src/utils.rs
tests/ui/pin_project/invalid.stderr
tests/ui/project/invalid.stderr

Update proc-macro2, syn, and quote to 1.0

---

examples/pinned_drop-expanded.rs
pin-project-internal/Cargo.toml
pin-project-internal/src/lib.rs
pin-project-internal/src/pin_project/attribute.rs
pin-project-internal/src/pinned_drop.rs
src/lib.rs
tests/ui/pinned_drop/forget-pinned-drop.stderr
tests/ui/pinned_drop/invalid.stderr

https://github.com/taiki-e/pin-project/pull/86#issuecomment-530478683

Make PinnedDrop safe trait

---

Cargo.toml
tests/ui/unstable-features/marker_trait_attr-feature-gate.rs
tests/ui/unstable-features/marker_trait_attr-feature-gate.stderr
tests/ui/unstable-features/marker_trait_attr.rs
tests/ui/unstable-features/marker_trait_attr.stderr

Add ui test for marker_trait_attr feature

---

Cargo.toml
tests/doc/Cargo.toml
tests/doc/build.rs
tests/doc/src/lib.rs

Test readme using rustdoc

---

.github/workflows/ci.yml
ci/install-component.sh
ci/install-rust.sh
examples/enum-default-expanded.rs
examples/enum-default.rs
examples/pinned_drop-expanded.rs
examples/pinned_drop.rs
examples/struct-default-expanded.rs
examples/struct-default.rs
examples/unsafe_unpin-expanded.rs
examples/unsafe_unpin.rs
tests/ui/pin_project/unpin_sneaky.stderr

This moves install scripts to own files and perform more correct checks
by using cargo-hack.

Cleanup CI config

---

tests/pin_project.rs

Refs: https://github.com/taiki-e/pin-project-lite/pull/6, https://github.com/taiki-e/pin-project-lite/pull/7

Add some tests

---

pin-project-internal/src/utils.rs
tests/pinned_drop.rs
tests/ui/pinned_drop/self.rs
tests/ui/pinned_drop/self.stderr

Based on https://github.com/dtolnay/async-trait/blob/0.1.30/src/receiver.rs

Improve handling of Self

---

pin-project-internal/src/pin_project/attribute.rs
pin-project-internal/src/pin_project/derive.rs
pin-project-internal/src/pinned_drop.rs
pin-project-internal/src/utils.rs

Given we have another hidden module, this doesn't seem to make much sense.

Remove CURRENT_PRIVATE_MODULE

---

tests/pin_project.rs

Refs: 
* https://github.com/rust-lang/rust/issues/47949
* https://github.com/taiki-e/pin-project/pull/194#discussion_r419098111

Add test for project_replace on panic

---

examples/not_unpin-expanded.rs
examples/pinned_drop-expanded.rs
examples/project_replace-expanded.rs
examples/struct-default-expanded.rs
examples/unsafe_unpin-expanded.rs
pin-project-internal/src/pin_project/derive.rs
tests/expand/tests/expand/default-struct.expanded.rs
tests/expand/tests/expand/default-tuple_struct.expanded.rs
tests/expand/tests/expand/naming-struct.expanded.rs
tests/expand/tests/expand/naming-tuple_struct.expanded.rs
tests/expand/tests/expand/not_unpin-struct.expanded.rs
tests/expand/tests/expand/not_unpin-tuple_struct.expanded.rs
tests/expand/tests/expand/pinned_drop-struct.expanded.rs
tests/expand/tests/expand/pinned_drop-tuple_struct.expanded.rs
tests/expand/tests/expand/project_replace-struct.expanded.rs
tests/expand/tests/expand/project_replace-tuple_struct.expanded.rs
tests/expand/tests/expand/pub-struct.expanded.rs
tests/expand/tests/expand/pub-tuple_struct.expanded.rs
tests/expand/tests/expand/unsafe_unpin-struct.expanded.rs
tests/expand/tests/expand/unsafe_unpin-tuple_struct.expanded.rs
tests/lint.rs

Fix unused_results lint in generated code

---

pin-project-internal/src/lib.rs

Addresses https://github.com/taiki-e/pin-project/pull/244#issuecomment-643601549

Add deprecation note to project attributes

---

pin-project-internal/src/lib.rs

Fix a typo in attr doc

---

tests/lint.rs
tests/lint.txt

Some lints should be used at crate level.

Fix lint test

---

examples/enum-default-expanded.rs
examples/project_replace-expanded.rs
examples/struct-default-expanded.rs
pin-project-internal/src/pin_project/derive.rs
src/lib.rs
tests/expand/tests/expand/default-enum.expanded.rs
tests/expand/tests/expand/default-struct.expanded.rs
tests/expand/tests/expand/default-tuple_struct.expanded.rs
tests/expand/tests/expand/naming-enum.expanded.rs
tests/expand/tests/expand/naming-struct.expanded.rs
tests/expand/tests/expand/naming-tuple_struct.expanded.rs
tests/expand/tests/expand/pinned_drop-enum.expanded.rs
tests/expand/tests/expand/pinned_drop-struct.expanded.rs
tests/expand/tests/expand/pinned_drop-tuple_struct.expanded.rs
tests/expand/tests/expand/project_replace-enum.expanded.rs
tests/expand/tests/expand/project_replace-struct.expanded.rs
tests/expand/tests/expand/project_replace-tuple_struct.expanded.rs
tests/expand/tests/expand/pub-enum.expanded.rs
tests/expand/tests/expand/pub-struct.expanded.rs
tests/expand/tests/expand/pub-tuple_struct.expanded.rs
tests/sized.rs

This is a fix for https://github.com/taiki-e/pin-project/issues/262. Feel free to disregard and implement differently if there is a better fix I'm missing.
Fixes: #262

Fix ?Sized type parameters

---

CHANGELOG.md
Cargo.toml
README.md
examples/README.md
pin-project-internal/Cargo.toml
pin-project-internal/src/lib.rs
src/lib.rs

[Changes](https://github.com/taiki-e/pin-project/blob/a1da018ce82073aec4d76bfdfa554c297bd77bd3/CHANGELOG.md#100-alpha1---2020-09-22)
cc #264

Release 1.0.0-alpha.1

---

pin-project-internal/src/pin_project/derive.rs
tests/expand/tests/expand/default-enum.expanded.rs
tests/expand/tests/expand/default-struct.expanded.rs
tests/expand/tests/expand/default-tuple_struct.expanded.rs
tests/expand/tests/expand/naming-enum.expanded.rs
tests/expand/tests/expand/naming-struct.expanded.rs
tests/expand/tests/expand/naming-tuple_struct.expanded.rs
tests/expand/tests/expand/not_unpin-enum.expanded.rs
tests/expand/tests/expand/not_unpin-struct.expanded.rs
tests/expand/tests/expand/not_unpin-tuple_struct.expanded.rs
tests/expand/tests/expand/project_replace-enum.expanded.rs
tests/expand/tests/expand/project_replace-struct.expanded.rs
tests/expand/tests/expand/project_replace-tuple_struct.expanded.rs
tests/expand/tests/expand/pub-enum.expanded.rs
tests/expand/tests/expand/pub-struct.expanded.rs
tests/expand/tests/expand/pub-tuple_struct.expanded.rs
tests/expand/tests/expand/unsafe_unpin-enum.expanded.rs
tests/expand/tests/expand/unsafe_unpin-struct.expanded.rs
tests/expand/tests/expand/unsafe_unpin-tuple_struct.expanded.rs
tests/lint.rs
tests/lint.txt

This is the backport of #273 
cc #272

v0.4: Prepare for uplift of drop-bounds lint

---

pin-project-internal/Cargo.toml
tests/auxiliary/macro/Cargo.toml

https://github.com/rust-lang/rust/pull/77135#issuecomment-706681588

Update minimal version of syn to 1.0.44

---

.github/dependabot.yml
.github/workflows/pr.yml

Refs: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-dependabot-version-updates

ci: Set up dependabot v2

---

.github/workflows/ci.yml
scripts/check-minimal-versions.sh

https://github.com/taiki-e/cargo-hack/pull/102

ci: make sure can compile with all versions on or after MSRV

---

tests/compiletest.rs
tests/ui/cfg/packed_sneaky-span-issue-1.rs
tests/ui/cfg/packed_sneaky-span-issue-1.stderr
tests/ui/cfg/packed_sneaky-span-issue-2.rs
tests/ui/cfg/packed_sneaky-span-issue-2.stderr
tests/ui/cfg/unsupported.rs
tests/ui/cfg/unsupported.stderr

Seems the span issue has been fixed 🎉

Update ui tests to nightly-2021-01-09

---

examples/project_replace-expanded.rs
pin-project-internal/src/pin_project/derive.rs
tests/expand/multifields/enum.expanded.rs
tests/expand/multifields/struct.expanded.rs
tests/expand/multifields/tuple_struct.expanded.rs
tests/expand/naming/enum-all.expanded.rs
tests/expand/naming/enum-own.expanded.rs
tests/expand/naming/struct-all.expanded.rs
tests/expand/naming/struct-own.expanded.rs
tests/expand/naming/tuple_struct-all.expanded.rs
tests/expand/naming/tuple_struct-own.expanded.rs
tests/expand/project_replace/enum.expanded.rs
tests/expand/project_replace/struct.expanded.rs
tests/expand/project_replace/tuple_struct.expanded.rs
tests/ui/pin_project/project_replace_unsized.stderr
tests/ui/pin_project/project_replace_unsized_fn_params.stderr

Based on https://github.com/taiki-e/pin-project-lite/commit/51fc92690b751a05389a1780d259b727ac406b1f.

Reduce code generated for project_replace for enums

---

tests/compiletest.rs
tests/no-core/Cargo.toml
tests/no-core/lib.rs
tests/ui/pin_project/packed_sneaky-3.stderr

Fix broken test

---

tests/compiletest.rs
tests/run-pass/negative_impls.rs

Add test for #340
